import type { Metadata } from "next";
import { LocaleProvider, ThemeProvider } from "@/components/Providers";
import type { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "../components/Providers";
import { getCurrentUser } from "@/services/user";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased h-screen`}>
        <SessionProvider>
          <AuthProvider user={user}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <LocaleProvider>{children}</LocaleProvider>
            </ThemeProvider>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
